#!/usr/bin/env python3
"""Verify the public deterministic KR-4974 NativeDisc cold-build fixture.

This verifier deliberately does not import the writer.  It reconstructs the
logical ISO image, parses every workload table and derives the advertised
counts from the generated bytes.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import stat
import struct
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path, PurePosixPath
from typing import Any, Iterable


SCHEMA = "katana-native-disc-cold-build-stress-v3"
SCHEMA_VERSION = 3
ROOT_SCHEMA_VERSION = 2
WORKLOAD_SCHEMA = "katana-native-disc-workload-v3"
WORKLOAD_SCHEMA_VERSION = 3
PROVENANCE_CONTRACT_VERSION = 3
DELTA_SCALE_FUNCTION_COUNTS = [16, 128]
REQUIRED_FUNCTION_VALUE_SUBPHASES = [
    "inventory-region-closure",
    "inventory-region-sink-sources",
    "abi-return-signatures",
    "abi-stack-reads",
    "abi-register-reads",
    "persistent-store-signatures",
    "inventory-reachability",
    "cache-key-plan",
    "resolution-root-dependencies",
    "resolution-root-scc-order",
    "resolution-root-scc-components",
    "resolution-root-contracts",
    "resolution-root-plan",
]
LOGICAL_SECTOR_SIZE = 2048
RAW_SECTOR_SIZE = 2352
DATA_TRACK_LBA = 45_000
BOOT_ADDRESS = 0x8C01_0000
SEMANTIC_ADDRESS = 0x8D00_0000
FUNCTION_SIZE = 0x38
BLOCKS_PER_FUNCTION = 14
SEMANTIC_HEAVY_BLOCKS = 4_096
SEMANTIC_ROOT_TAIL = SEMANTIC_HEAVY_BLOCKS * 4
SEMANTIC_SIZE = 0x5148
ROOT_MAGIC = b"KSTRROOT"
DETERMINISTIC_SEED = 0x00C0FFEE
RESOLUTION_PROBE_VALUE_BLOCK = 0
RESOLUTION_PROBE_STORE_BLOCK = 1
RESOLUTION_PROBE_LOAD_BLOCK = 2
MANIFEST_NAME = "stress-manifest.json"
MANIFEST_DIGEST_NAME = "stress-manifest.sha256"
SHA256_RE = re.compile(r"[0-9a-f]{64}")
OVERRIDE_RE = re.compile(
    r"function = 0x([0-9A-Fa-f]{8}) 0x([0-9A-Fa-f]{8})"
)
MODULE_NAME_RE = re.compile(r"M([0-9]{3})\.BIN;1")


class VerificationError(RuntimeError):
    """A stable, user-facing fixture contract violation."""


@dataclass(frozen=True)
class Profile:
    name: str
    functions: int
    roots: int
    wave_sizes: tuple[int, ...]
    partitions: int
    modules: int
    chunks_per_module: int
    chunk_size: int
    replay_passes: int

    @property
    def basic_blocks(self) -> int:
        return self.functions * BLOCKS_PER_FUNCTION

PROFILES = {
    "smoke": Profile(
        name="smoke",
        functions=16,
        roots=14,
        wave_sizes=(8, 3, 2, 1),
        partitions=4,
        modules=2,
        chunks_per_module=2,
        chunk_size=256,
        replay_passes=1,
    ),
    "reference": Profile(
        name="reference",
        functions=1_600,
        roots=1_400,
        wave_sizes=(800, 240, 120, 80, 60, 40, 30, 30),
        partitions=64,
        modules=32,
        chunks_per_module=8,
        chunk_size=512,
        replay_passes=53,
    ),
}

EXPECTED_MANIFEST_DIGESTS = {
    "smoke": "861af21607d2cdb1a1a8ea2a2ca5d85b0bab5995d58f4e62a49515bf94e818c6",
    "reference": "dbe0500286adc3e05de122a99769707e83e95302f4376ee608631864ac12af55",
}


@dataclass(frozen=True)
class DirectoryEntry:
    name: bytes
    extent: int
    size: int
    directory: bool


@dataclass(frozen=True)
class Fixture:
    root: Path
    manifest: dict[str, Any]
    profile: Profile
    iso_files: dict[str, bytes]


def require(condition: bool, message: str) -> None:
    if not condition:
        raise VerificationError(message)


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def read_regular(path: Path, description: str) -> bytes:
    try:
        info = path.lstat()
    except OSError as error:
        raise VerificationError(f"{description} fehlt: {path.name}") from error
    require(stat.S_ISREG(info.st_mode), f"{description} ist keine regulaere Datei: {path.name}")
    require(not path.is_symlink(), f"{description} darf kein Symlink sein: {path.name}")
    try:
        return path.read_bytes()
    except OSError as error:
        raise VerificationError(f"{description} konnte nicht gelesen werden: {path.name}") from error


def unique_json_pairs(pairs: list[tuple[str, Any]]) -> dict[str, Any]:
    result: dict[str, Any] = {}
    for key, value in pairs:
        if key in result:
            raise VerificationError(f"JSON besitzt doppeltes Feld: {key}")
        result[key] = value
    return result


def reject_json_constant(value: str) -> None:
    raise VerificationError(f"JSON besitzt nicht-endlichen Zahlenwert: {value}")


def parse_json_bytes(data: bytes, description: str) -> Any:
    try:
        text = data.decode("utf-8")
    except UnicodeDecodeError as error:
        raise VerificationError(f"{description} ist kein UTF-8") from error
    require("\r" not in text, f"{description} besitzt keine kanonischen LF-Zeilenenden")
    try:
        return json.loads(
            text,
            object_pairs_hook=unique_json_pairs,
            parse_constant=reject_json_constant,
        )
    except (json.JSONDecodeError, TypeError) as error:
        raise VerificationError(f"{description} ist kein gueltiges JSON: {error}") from error


def canonical_json(value: Any) -> bytes:
    return (json.dumps(value, indent=2, sort_keys=True) + "\n").encode("utf-8")


def as_mapping(value: Any, description: str) -> dict[str, Any]:
    require(isinstance(value, dict), f"{description} muss ein JSON-Objekt sein")
    return value


def as_list(value: Any, description: str) -> list[Any]:
    require(isinstance(value, list), f"{description} muss ein JSON-Array sein")
    return value


def exact_int(value: Any, description: str) -> int:
    require(
        isinstance(value, int) and not isinstance(value, bool),
        f"{description} muss eine Ganzzahl sein",
    )
    return value


def relative_artifact_path(value: Any, description: str) -> str:
    require(isinstance(value, str) and value, f"{description} muss ein Dateiname sein")
    parsed = PurePosixPath(value)
    require(
        not parsed.is_absolute()
        and len(parsed.parts) == 1
        and parsed.parts[0] not in (".", "..")
        and "\\" not in value,
        f"{description} muss ein relativer Top-Level-Dateiname sein",
    )
    return value


def read_le16(data: bytes, offset: int) -> int:
    require(offset + 2 <= len(data), "Abgeschnittenes Little-Endian-16-Feld")
    return int.from_bytes(data[offset : offset + 2], "little")


def read_be16(data: bytes, offset: int) -> int:
    require(offset + 2 <= len(data), "Abgeschnittenes Big-Endian-16-Feld")
    return int.from_bytes(data[offset : offset + 2], "big")


def read_le32(data: bytes, offset: int) -> int:
    require(offset + 4 <= len(data), "Abgeschnittenes Little-Endian-32-Feld")
    return int.from_bytes(data[offset : offset + 4], "little")


def read_be32(data: bytes, offset: int) -> int:
    require(offset + 4 <= len(data), "Abgeschnittenes Big-Endian-32-Feld")
    return int.from_bytes(data[offset : offset + 4], "big")


def read_both16(data: bytes, offset: int, description: str) -> int:
    little = read_le16(data, offset)
    big = read_be16(data, offset + 2)
    require(little == big, f"{description}: Both-Endian-16-Werte widersprechen sich")
    return little


def read_both32(data: bytes, offset: int, description: str) -> int:
    little = read_le32(data, offset)
    big = read_be32(data, offset + 4)
    require(little == big, f"{description}: Both-Endian-32-Werte widersprechen sich")
    return little


def parse_directory_record(data: bytes, offset: int, description: str) -> tuple[DirectoryEntry, int]:
    require(offset < len(data), f"{description}: Directory-Offset liegt ausserhalb")
    length = data[offset]
    require(length >= 34, f"{description}: Directory-Record ist zu kurz")
    require(offset + length <= len(data), f"{description}: Directory-Record ist abgeschnitten")
    extent = read_both32(data, offset + 2, f"{description} Extent")
    size = read_both32(data, offset + 10, f"{description} Groesse")
    require(read_both16(data, offset + 28, f"{description} Volume") == 1, f"{description}: Volume != 1")
    name_length = data[offset + 32]
    require(33 + name_length <= length, f"{description}: Dateiname ist abgeschnitten")
    expected_length = 33 + name_length + (1 if name_length % 2 == 0 else 0)
    require(length == expected_length, f"{description}: nicht-kanonische Recordlaenge")
    name = data[offset + 33 : offset + 33 + name_length]
    return DirectoryEntry(name, extent, size, bool(data[offset + 25] & 0x02)), length


def parse_gdi(root: Path) -> tuple[bytes, bytes, bytes]:
    descriptor = read_regular(root / "disc.gdi", "GDI-Deskriptor")
    expected = (
        b"3\n"
        b"1 0 4 2352 track01.bin 0\n"
        b"2 30 0 2352 track02.raw 0\n"
        b"3 45000 4 2352 track03.bin 0\n"
    )
    require(descriptor == expected, "disc.gdi verletzt den kanonischen Drei-Track-Vertrag")
    low = read_regular(root / "track01.bin", "Low-Density-Datentrack")
    audio = read_regular(root / "track02.raw", "Audio-Track")
    high = read_regular(root / "track03.bin", "High-Density-Datentrack")
    require(len(low) == 24 * RAW_SECTOR_SIZE, "track01.bin muss genau 24 Rohsektoren besitzen")
    require(len(audio) == 4 * RAW_SECTOR_SIZE, "track02.raw muss genau vier Rohsektoren besitzen")
    require(
        len(high) >= 22 * RAW_SECTOR_SIZE and len(high) % RAW_SECTOR_SIZE == 0,
        "track03.bin besitzt keine gueltige Rohsektorgroesse",
    )
    return low, audio, high


def binary_coded_decimal(value: int) -> int:
    require(0 <= value <= 99, "BCD-Wert liegt ausserhalb")
    return ((value // 10) << 4) | (value % 10)


def mode1_payload(raw_track: bytes, description: str, first_lba: int) -> bytes:
    require(len(raw_track) % RAW_SECTOR_SIZE == 0, f"{description} ist nicht sektoral ausgerichtet")
    result = bytearray()
    for index in range(len(raw_track) // RAW_SECTOR_SIZE):
        sector = raw_track[index * RAW_SECTOR_SIZE : (index + 1) * RAW_SECTOR_SIZE]
        require(
            sector[:12] == b"\x00" + b"\xff" * 10 + b"\x00",
            f"{description} Sektor {index} besitzt keinen kanonischen Sync-Header",
        )
        absolute_frame = first_lba + index + 150
        expected_address = bytes(
            (
                binary_coded_decimal((absolute_frame // (75 * 60)) % 100),
                binary_coded_decimal((absolute_frame // 75) % 60),
                binary_coded_decimal(absolute_frame % 75),
            )
        )
        require(
            sector[12:15] == expected_address,
            f"{description} Sektor {index} besitzt eine falsche MSF-Adresse",
        )
        require(sector[15] == 1, f"{description} Sektor {index} ist kein Mode1-Sektor")
        require(
            all(byte == 0 for byte in sector[16 + LOGICAL_SECTOR_SIZE :]),
            f"{description} Sektor {index} besitzt nicht-kanonische Zusatzbytes",
        )
        result.extend(sector[16 : 16 + LOGICAL_SECTOR_SIZE])
    return bytes(result)


def verify_synthetic_low_track(logical: bytes) -> None:
    marker = (
        b"KATANA RECOMP SYNTHETIC LOW-DENSITY TRACK; "
        b"NO RETAIL CONTENT; KR-4974 CONTRACT 1\n"
    )
    require(len(logical) == 24 * LOGICAL_SECTOR_SIZE, "Low-Density-Nutzdatenlaenge falsch")
    for sector_index in range(24):
        expected = bytearray(LOGICAL_SECTOR_SIZE)
        expected[: len(marker)] = marker
        expected[128:132] = sector_index.to_bytes(4, "little")
        sector = logical[
            sector_index * LOGICAL_SECTOR_SIZE : (sector_index + 1) * LOGICAL_SECTOR_SIZE
        ]
        require(sector == expected, f"Low-Density-Sektor {sector_index} ist nicht oeffentlich synthetisch")


def verify_synthetic_audio(data: bytes) -> None:
    expected = bytearray(len(data))
    state = 0x00C0FFEE
    for index in range(len(expected)):
        state = (state * 1_664_525 + 1_013_904_223) & 0xFFFF_FFFF
        expected[index] = (state >> 24) & 0xFF
    require(data == expected, "Audio-Track stimmt nicht mit dem oeffentlichen LCG-Vertrag ueberein")


def translated_extent(extent: int, relative_extents: bool) -> int:
    if relative_extents:
        require(extent < DATA_TRACK_LBA, "ISO mischt relative und absolute Extents")
        return extent
    require(extent >= DATA_TRACK_LBA, "ISO mischt absolute und relative Extents")
    return extent - DATA_TRACK_LBA


def verify_path_table(
    logical: bytes,
    pvd: bytes,
    root_sector: int,
    relative_extents: bool,
) -> None:
    path_size = read_both32(pvd, 132, "ISO Path-Table-Groesse")
    require(path_size == 10, "ISO muss eine kanonische Eintrags-Path-Table besitzen")
    little_lba = read_le32(pvd, 140)
    big_lba = read_be32(pvd, 148)
    require(
        little_lba == DATA_TRACK_LBA + 18 and big_lba == DATA_TRACK_LBA + 19,
        "ISO Path-Tables muessen absolut auf Discsektor 45018/45019 liegen",
    )
    little_sector = translated_extent(little_lba, relative_extents)
    big_sector = translated_extent(big_lba, relative_extents)
    little = logical[little_sector * LOGICAL_SECTOR_SIZE : little_sector * LOGICAL_SECTOR_SIZE + path_size]
    big = logical[big_sector * LOGICAL_SECTOR_SIZE : big_sector * LOGICAL_SECTOR_SIZE + path_size]
    require(len(little) == path_size and len(big) == path_size, "ISO Path-Table ist abgeschnitten")
    require(little[0:2] == b"\x01\x00" and big[0:2] == b"\x01\x00", "ISO Root-Path-Record ungueltig")
    little_extent = read_le32(little, 2)
    big_extent = read_be32(big, 2)
    require(
        translated_extent(little_extent, relative_extents) == root_sector
        and translated_extent(big_extent, relative_extents) == root_sector,
        "ISO Path-Table verweist nicht auf Root",
    )
    require(read_le16(little, 6) == 1 and read_be16(big, 6) == 1, "ISO Root-Parent muss 1 sein")
    require(little[8:] == b"\x00\x00" and big[8:] == b"\x00\x00", "ISO Root-Pathname ungueltig")


def parse_iso(high: bytes) -> tuple[dict[str, bytes], dict[str, DirectoryEntry]]:
    logical = mode1_payload(high, "track03.bin", DATA_TRACK_LBA)
    require(len(logical) % LOGICAL_SECTOR_SIZE == 0, "Logische ISO ist nicht sektoral")
    volume_sectors = len(logical) // LOGICAL_SECTOR_SIZE
    ip = logical[:LOGICAL_SECTOR_SIZE]
    require(ip[0:16].rstrip(b" \0") == b"SEGA SEGAKATANA", "IP.BIN-Hardwarekennung ungueltig")
    require(ip[0x25:0x2B].rstrip(b" \0") == b"GD-ROM", "IP.BIN ist nicht als GD-ROM markiert")
    require(ip[0x3E] != ord("1"), "IP.BIN markiert einen nicht unterstuetzten WinCE-Boot")
    require(ip[0x60:0x70].rstrip(b" \0") == b"BOOT.BIN", "IP.BIN-Bootdateiname ungueltig")
    expected_bootstrap = bytes(
        (0x01, 0xD0, 0x2B, 0x40, 0x09, 0x00, 0x09, 0x00, 0x00, 0x00, 0x01, 0x8C)
    )
    require(ip[0x300 : 0x300 + len(expected_bootstrap)] == expected_bootstrap, "IP.BIN-Bootstrap ungueltig")

    pvd = logical[16 * LOGICAL_SECTOR_SIZE : 17 * LOGICAL_SECTOR_SIZE]
    terminator = logical[17 * LOGICAL_SECTOR_SIZE : 18 * LOGICAL_SECTOR_SIZE]
    require(pvd[0:7] == b"\x01CD001\x01", "ISO Primary Volume Descriptor ungueltig")
    require(terminator[0:7] == b"\xffCD001\x01", "ISO Volume Descriptor Terminator fehlt")
    require(read_both16(pvd, 128, "ISO Blockgroesse") == LOGICAL_SECTOR_SIZE, "ISO Blockgroesse != 2048")
    require(
        read_both32(pvd, 80, "ISO Volumegroesse") == DATA_TRACK_LBA + volume_sectors,
        "ISO absolute Volumegroesse falsch",
    )

    root_entry, _ = parse_directory_record(pvd, 156, "PVD-Root")
    require(root_entry.name == b"\x00" and root_entry.directory, "PVD-Rootrecord ungueltig")
    relative_extents = root_entry.extent < DATA_TRACK_LBA
    require(not relative_extents, "KR-4974-ISO muss absolute Disc-Extents verwenden")
    root_sector = translated_extent(root_entry.extent, relative_extents)
    require(root_sector == 20, "ISO Rootverzeichnis muss in Sektor 20 liegen")
    require(root_entry.size == LOGICAL_SECTOR_SIZE, "ISO Rootverzeichnis muss einen Sektor gross sein")
    verify_path_table(logical, pvd, root_sector, relative_extents)

    root_start = root_sector * LOGICAL_SECTOR_SIZE
    root_data = logical[root_start : root_start + root_entry.size]
    require(len(root_data) == root_entry.size, "ISO Rootverzeichnis ist abgeschnitten")
    entries: dict[str, DirectoryEntry] = {}
    offset = 0
    dot_names: list[bytes] = []
    while offset < len(root_data):
        if root_data[offset] == 0:
            require(all(byte == 0 for byte in root_data[offset:]), "ISO Rootpadding ist nicht null")
            break
        entry, length = parse_directory_record(root_data, offset, f"ISO Rootrecord {len(entries)}")
        if entry.name in (b"\x00", b"\x01"):
            dot_names.append(entry.name)
            require(entry.directory, "ISO Punktrecord ist kein Verzeichnis")
            require(
                translated_extent(entry.extent, relative_extents) == root_sector
                and entry.size == root_entry.size,
                "ISO Punktrecord verweist nicht auf Root",
            )
        else:
            try:
                name = entry.name.decode("ascii")
            except UnicodeDecodeError as error:
                raise VerificationError("ISO-Dateiname ist nicht ASCII") from error
            require(not entry.directory, f"Unerwartetes Unterverzeichnis: {name}")
            require(name not in entries, f"Doppelter ISO-Dateiname: {name}")
            require(re.fullmatch(r"[A-Z0-9_]{1,8}\.[A-Z0-9]{1,3};1", name) is not None, f"Unsicherer ISO-Dateiname: {name}")
            entries[name] = entry
        offset += length
    require(dot_names == [b"\x00", b"\x01"], "ISO Root braucht genau Punkt und Doppelpunkt")

    files: dict[str, bytes] = {}
    occupied: list[tuple[int, int, str]] = [(0, 21, "ISO-Systembereich")]
    for name, entry in sorted(entries.items()):
        sector = translated_extent(entry.extent, relative_extents)
        sector_count = (entry.size + LOGICAL_SECTOR_SIZE - 1) // LOGICAL_SECTOR_SIZE
        require(sector >= 21 and sector_count > 0, f"{name}: ungueltiger Datei-Extent")
        require(sector + sector_count <= volume_sectors, f"{name}: Datei-Extent liegt ausserhalb")
        for begin, end, previous_name in occupied:
            require(
                sector + sector_count <= begin or sector >= end,
                f"{name}: Datei-Extent ueberlappt {previous_name}",
            )
        occupied.append((sector, sector + sector_count, name))
        start = sector * LOGICAL_SECTOR_SIZE
        files[name] = logical[start : start + entry.size]
        padding = logical[start + entry.size : (sector + sector_count) * LOGICAL_SECTOR_SIZE]
        require(all(byte == 0 for byte in padding), f"{name}: Datei-Padding ist nicht null")
    ranges = sorted(occupied[1:])
    cursor = 21
    for begin, end, name in ranges:
        require(begin == cursor, f"ISO besitzt vor {name} eine unnoetige Extent-Luecke")
        cursor = end
    require(cursor == volume_sectors, "ISO besitzt nach dem letzten Extent unnoetige Sektoren")
    return files, entries


def expected_wave(profile: Profile, root_index: int) -> int:
    cursor = 0
    for wave, count in enumerate(profile.wave_sizes):
        cursor += count
        if root_index < cursor:
            return wave
    raise VerificationError(f"Root {root_index} liegt ausserhalb der Seed-Wellen")


def verify_boot(boot: bytes, profile: Profile) -> None:
    require(len(boot) == profile.functions * FUNCTION_SIZE, "BOOT.BIN besitzt falsche Groesse")
    resolution_roots = {
        (root_index * 37) % profile.functions for root_index in range(profile.roots)
    }
    require(
        len(resolution_roots) == profile.roots,
        "BOOT.BIN Resolution-Root-Menge ist nicht eindeutig",
    )
    for function_index in range(profile.functions):
        function = boot[function_index * FUNCTION_SIZE : (function_index + 1) * FUNCTION_SIZE]
        for block_index in range(BLOCKS_PER_FUNCTION):
            offset = block_index * 4
            control = read_le16(function, offset)
            delay = read_le16(function, offset + 2)
            if block_index + 1 == BLOCKS_PER_FUNCTION:
                require(control == 0x000B, f"BOOT Funktion {function_index}: Abschluss ist kein rts")
                require(
                    delay == 0x0009,
                    f"BOOT Funktion {function_index}: rts-Delay-Slot ist kein nop",
                )
            else:
                require(control == 0xA000, f"BOOT Funktion {function_index} Block {block_index}: kein bra 0")
                register = (function_index + block_index) & 0x0F
                immediate = (
                    function_index * 29
                    + block_index * 17
                    + DETERMINISTIC_SEED
                ) & 0xFF
                expected_delay = 0xE000 | (register << 8) | immediate
                if function_index in resolution_roots:
                    if block_index == RESOLUTION_PROBE_VALUE_BLOCK:
                        expected_delay = 0xE000 | immediate
                    elif block_index == RESOLUTION_PROBE_STORE_BLOCK:
                        expected_delay = 0x2F06
                    elif block_index == RESOLUTION_PROBE_LOAD_BLOCK:
                        expected_delay = 0x60F6
                require(
                    delay == expected_delay,
                    f"BOOT Funktion {function_index} Block {block_index}: "
                    "kein exakter deterministischer BRA-/Resolution-Delay-Slot",
                )


def verify_overrides(data: bytes, profile: Profile) -> None:
    try:
        text = data.decode("ascii")
    except UnicodeDecodeError as error:
        raise VerificationError("analysis.overrides ist nicht ASCII") from error
    require("\r" not in text and text.endswith("\n"), "analysis.overrides braucht kanonische LF-Zeilen")
    lines = text.splitlines()
    require(
        lines[:3]
        == [
            "version = 2",
            "schema = katana-analysis-directives",
            "mode = override",
        ],
        "analysis.overrides besitzt keinen kanonischen Header",
    )
    require(len(lines) == profile.functions + 3, "analysis.overrides besitzt falsche Funktionszahl")
    for index, line in enumerate(lines[3:]):
        match = OVERRIDE_RE.fullmatch(line)
        require(match is not None, f"analysis.overrides Zeile {index + 4} ungueltig")
        address = int(match.group(1), 16)
        size = int(match.group(2), 16)
        require(address == BOOT_ADDRESS + index * FUNCTION_SIZE, f"Override {index}: falsche Adresse")
        require(size == FUNCTION_SIZE, f"Override {index}: falsche Funktionsgroesse")


def verify_roots(data: bytes, profile: Profile) -> list[int]:
    header = struct.Struct("<8sIIII")
    record = struct.Struct("<IIIII")
    require(len(data) >= header.size, "ROOTS.BIN ist abgeschnitten")
    magic, version, count, record_size, wave_count = header.unpack_from(data)
    require(
        magic == ROOT_MAGIC and version == ROOT_SCHEMA_VERSION,
        "ROOTS.BIN Header ungueltig",
    )
    require(count == profile.roots and record_size == record.size, "ROOTS.BIN Counts ungueltig")
    require(wave_count == len(profile.wave_sizes), "ROOTS.BIN Wellenzahl ungueltig")
    require(len(data) == header.size + count * record.size, "ROOTS.BIN Groesse ungueltig")
    result: list[int] = []
    seen_functions: set[int] = set()
    for index in range(count):
        root_index, function_index, wave, expected_blocks, reserved = record.unpack_from(
            data, header.size + index * record.size
        )
        require(root_index == index, f"ROOTS.BIN Record {index}: instabiler Index")
        expected_function = (index * 37) % profile.functions
        require(function_index == expected_function, f"ROOTS.BIN Record {index}: falsche Funktion")
        expected_seed_wave = expected_wave(profile, index)
        require(wave == expected_seed_wave, f"ROOTS.BIN Record {index}: falsche Seed-Welle")
        require(
            expected_blocks == BLOCKS_PER_FUNCTION and reserved == 0,
            f"ROOTS.BIN Record {index}: kein reiner Realanalysevertrag",
        )
        require(function_index not in seen_functions, f"ROOTS.BIN Record {index}: Funktion dupliziert")
        seen_functions.add(function_index)
        result.append(function_index)
    return result


def field(mapping: dict[str, Any], names: Iterable[str], description: str) -> Any:
    found = [name for name in names if name in mapping]
    require(len(found) == 1, f"{description}: genau eines von {', '.join(names)} erwartet")
    return mapping[found[0]]


def expected_workload(profile: Profile) -> dict[str, Any]:
    return {
        "block_count": profile.basic_blocks,
        "blocks_per_function": BLOCKS_PER_FUNCTION,
        "chunk_size": profile.chunk_size,
        "chunks_per_module": profile.chunks_per_module,
        "declared_entry_count": profile.modules + 1,
        "declared_hint_count": profile.modules + 3,
        "declared_source_binding_count": profile.modules + 1,
        "cfa_delta_scale_function_counts": DELTA_SCALE_FUNCTION_COUNTS,
        "fva_delta_scale_function_counts": DELTA_SCALE_FUNCTION_COUNTS,
        "function_count": profile.functions,
        "module_count": profile.modules,
        "module_extent_count": profile.modules + 1,
        "partition_count": profile.partitions,
        "replay_passes": profile.replay_passes,
        "resolution_root_count": profile.roots,
        "resolution_root_probe": "r0-stack-roundtrip",
        "persistent_physical_work_contract": "kr-4978-v1",
        "required_function_value_subphases": REQUIRED_FUNCTION_VALUE_SUBPHASES,
        "root_count": profile.roots,
        "semantic_function_count": 6,
        "seed_wave_counts": list(profile.wave_sizes),
        "throughput_topology": "independent-bra-chains-with-resolution-roots",
        "wave_count": len(profile.wave_sizes),
    }


def verify_workload(data: bytes, profile: Profile) -> dict[str, Any]:
    workload = as_mapping(parse_json_bytes(data, "WORKLOAD.JSN"), "WORKLOAD.JSN")
    require(canonical_json(workload) == data, "WORKLOAD.JSN ist nicht kanonisch serialisiert")
    require(
        set(workload) == {"profile", "schema", "version", "workload"},
        "WORKLOAD.JSN besitzt unerwartete oder fehlende Top-Level-Felder",
    )
    require(workload["schema"] == WORKLOAD_SCHEMA, "Workload-Schema ungueltig")
    require(
        exact_int(workload["version"], "Workload-Version")
        == WORKLOAD_SCHEMA_VERSION,
        "Workload-Version ungueltig",
    )
    require(workload["profile"] == profile.name, "Workload-Profil falsch")
    require(
        as_mapping(workload["workload"], "Workload-Counts") == expected_workload(profile),
        "WORKLOAD.JSN besitzt nicht das exakte Profil",
    )
    return workload


def verify_partitions(data: bytes, profile: Profile) -> None:
    plan = as_mapping(parse_json_bytes(data, "PARTS.JSN"), "PARTS.JSN")
    require(canonical_json(plan) == data, "PARTS.JSN ist nicht kanonisch serialisiert")
    partitions: list[dict[str, Any]] = []
    for partition_index in range(profile.partitions):
        begin = partition_index * profile.functions // profile.partitions
        end = (partition_index + 1) * profile.functions // profile.partitions
        count = end - begin
        partitions.append(
            {
                "block_count": count * BLOCKS_PER_FUNCTION,
                "function_begin": begin,
                "function_count": count,
                "function_end": end,
                "index": partition_index,
            }
        )
    expected = {
        "block_count": profile.basic_blocks,
        "blocks_per_function": BLOCKS_PER_FUNCTION,
        "function_count": profile.functions,
        "partition_count": profile.partitions,
        "partitions": partitions,
        "profile": profile.name,
        "schema": "katana-stress-partition-plan-v2",
        "version": 2,
    }
    require(plan == expected, "PARTS.JSN besitzt nicht den exakten kanonischen Bootpartitionsplan")


def verify_semantic_program(data: bytes, contract_data: bytes) -> None:
    require(len(data) == SEMANTIC_SIZE, "SEMANTIC.BIN besitzt falsche Groesse")
    expected = bytearray((0x09, 0x00) * (SEMANTIC_SIZE // 2))

    def put_u16(offset: int, value: int) -> None:
        struct.pack_into("<H", expected, offset, value)

    def put_u32(offset: int, value: int) -> None:
        struct.pack_into("<I", expected, offset, value)

    for block_index in range(SEMANTIC_HEAVY_BLOCKS):
        offset = block_index * 4
        put_u16(offset, 0xA000)
        register = block_index & 0x0F
        immediate = (block_index * 17 + 12_648_430) & 0xFF
        put_u16(offset + 2, 0xE000 | (register << 8) | immediate)
    tail = SEMANTIC_ROOT_TAIL
    for offset, value in {
        tail + 0x00: 0xD007, tail + 0x02: 0x2F02,
        tail + 0x04: 0xD107, tail + 0x06: 0x410B,
        tail + 0x08: 0x0009, tail + 0x0A: 0x000B, tail + 0x0C: 0x0009,
        0x5000: 0x64F2, 0x5002: 0xD503, 0x5004: 0x2542,
        0x5006: 0xD107, 0x5008: 0x410B, 0x500A: 0x0009,
        0x500C: 0x000B, 0x500E: 0x0009,
        0x5040: 0xD107, 0x5042: 0x410B, 0x5044: 0x0009,
        0x5046: 0xD108, 0x5048: 0x410B, 0x504A: 0x0009,
        0x504C: 0x000B, 0x504E: 0x0009,
        0x5080: 0xD603, 0x5082: 0x2642, 0x5084: 0xD107,
        0x5086: 0x410B, 0x5088: 0x0009, 0x508A: 0x000B,
        0x508C: 0x0009, 0x50C0: 0x000B, 0x50C2: 0x0009,
        0x5100: 0x2F06, 0x5102: 0x60F6, 0x5104: 0x000B,
        0x5106: 0x0009,
    }.items():
        put_u16(offset, value)
    put_u32(tail + 0x20, SEMANTIC_ADDRESS + 0x50C0)
    put_u32(tail + 0x24, SEMANTIC_ADDRESS + 0x5000)
    put_u32(0x5010, SEMANTIC_ADDRESS + 0x5140)
    put_u32(0x5024, SEMANTIC_ADDRESS + 0x5040)
    put_u32(0x5060, SEMANTIC_ADDRESS + 0x5080)
    put_u32(0x5068, SEMANTIC_ADDRESS + 0x5000)
    put_u32(0x5090, SEMANTIC_ADDRESS + 0x5144)
    put_u32(0x50A4, SEMANTIC_ADDRESS + 0x50C0)
    put_u32(0x5140, 0)
    put_u32(0x5144, 0)
    require(data == bytes(expected), "SEMANTIC.BIN weicht vom Opcodevertrag ab")

    contract = as_mapping(parse_json_bytes(contract_data, "SEMANTIC.JSN"), "SEMANTIC.JSN")
    require(canonical_json(contract) == contract_data, "SEMANTIC.JSN ist nicht kanonisch")
    expected_contract = {
        "abi_stack_argument_slot": 0,
        "boundaries": [
            {"offset": 0x00, "size": SEMANTIC_ROOT_TAIL + 0x0E},
            {"offset": 0x5000, "size": 0x10},
            {"offset": 0x5040, "size": 0x10},
            {"offset": 0x5080, "size": 0x0E},
            {"offset": 0x50C0, "size": 0x04},
            {"offset": 0x5100, "size": 0x08},
        ],
        "call_chain": [0x00, 0x5000, 0x5040, 0x5080, 0x50C0],
        "heavy_prefix_blocks": SEMANTIC_HEAVY_BLOCKS,
        "indirect_call_sites": [
            SEMANTIC_ROOT_TAIL + 0x06,
            0x5008,
            0x5042,
            0x5048,
            0x5086,
        ],
        "load_address": "0x8d000000",
        "persistent_store_functions": [0x5000, 0x5080],
        "resolution_targets": [0x5000, 0x5040, 0x5080, 0x50C0],
        "schema": "katana-stress-semantic-graph-v1",
        "scc": [0x5000, 0x5040],
        "size": SEMANTIC_SIZE,
        "unaffected_functions": [0x5100],
        "version": 1,
    }
    require(contract == expected_contract, "SEMANTIC.JSN beschreibt nicht den exakten Graphen")


def verify_modules(files: dict[str, bytes], profile: Profile) -> None:
    modules = sorted(name for name in files if MODULE_NAME_RE.fullmatch(name))
    expected_names = [f"M{index:03d}.BIN;1" for index in range(profile.modules)]
    require(modules == expected_names, "ISO besitzt falsche Latent-Modulmenge")
    expected_size = profile.chunks_per_module * profile.chunk_size
    require(profile.chunk_size % 4 == 0, "Profil-Chunkgroesse ist nicht SH-4-ausgerichtet")
    digests: set[str] = set()
    for name in modules:
        data = files[name]
        require(len(data) == expected_size, f"{name} besitzt falsche Groesse")
        digest = sha256_bytes(data)
        require(digest not in digests, f"{name} dupliziert bytegleich ein anderes Modul")
        digests.add(digest)
        terminal_offsets = {len(data) - 4}
        if name == "M000.BIN;1":
            terminal_offsets.add(len(data) // 2 - 4)
        for offset in range(0, len(data), 4):
            control = read_le16(data, offset)
            delay = read_le16(data, offset + 2)
            if offset in terminal_offsets:
                require(control == 0x000B, f"{name}: Abschluss ist kein rts")
                require(delay == 0x0009, f"{name}: rts-Delay-Slot ist kein nop")
            else:
                require(control == 0xA000, f"{name}: kein bra 0 bei {offset}")
                require(delay & 0xF000 == 0xE000, f"{name}: ungueltiger Delay-Slot")
    duplicate = files.get("M000DUP.BIN;1")
    require(duplicate is not None, "ISO besitzt keinen zweiten bytegleichen Modul-Extent")
    require(duplicate == files["M000.BIN;1"], "zweiter Modul-Extent ist nicht bytegleich")


def verify_latent_hints(
    data: bytes,
    files: dict[str, bytes],
    entries: dict[str, DirectoryEntry],
    profile: Profile,
) -> None:
    try:
        text = data.decode("ascii")
    except UnicodeDecodeError as error:
        raise VerificationError("latent-aot-entries.txt ist nicht ASCII") from error
    require("\r" not in text and text.endswith("\n"), "Latent-AOT-Hints brauchen kanonische LF-Zeilen")
    candidates = []
    for module_index in range(profile.modules):
        name = f"M{module_index:03d}.BIN;1"
        payload = files[name]
        entry_offsets = (0, len(payload) // 2) if module_index == 0 else (0,)
        for entry_offset in entry_offsets:
            candidates.append(
                (
                    sha256_bytes(payload),
                    entries[name].extent * LOGICAL_SECTOR_SIZE,
                    len(payload),
                    entry_offset,
                )
            )
    duplicate_name = "M000DUP.BIN;1"
    duplicate = files[duplicate_name]
    for entry_offset in (0, len(duplicate) // 2):
        candidates.append(
            (
                sha256_bytes(duplicate),
                entries[duplicate_name].extent * LOGICAL_SECTOR_SIZE,
                len(duplicate),
                entry_offset,
            )
        )
    expected_lines = [
        f"sha256:{digest}@{offset}:{size}:{entry_offset}"
        for digest, offset, size, entry_offset in sorted(candidates)
    ]
    require(
        text.splitlines() == expected_lines,
        "Latent-AOT-Hints stimmen nicht exakt mit den ISO-Modulen ueberein",
    )


def manifest_artifacts(manifest: dict[str, Any]) -> dict[str, tuple[int, str]]:
    raw = field(manifest, ("artifacts",), "Manifest-Artefakte")
    result: dict[str, tuple[int, str]] = {}
    if isinstance(raw, dict):
        items = []
        for path, metadata in raw.items():
            item = as_mapping(metadata, f"Manifest-Artefakt {path}").copy()
            item["path"] = path
            items.append(item)
    else:
        items = as_list(raw, "Manifest-Artefakte")
    for index, raw_item in enumerate(items):
        item = as_mapping(raw_item, f"Manifest-Artefakt {index}")
        path = relative_artifact_path(field(item, ("path", "name"), f"Artefakt {index} Pfad"), f"Artefakt {index} Pfad")
        size = exact_int(field(item, ("size", "size_bytes", "bytes"), f"Artefakt {path} Groesse"), f"Artefakt {path} Groesse")
        digest = field(item, ("sha256",), f"Artefakt {path} SHA-256")
        require(isinstance(digest, str) and SHA256_RE.fullmatch(digest) is not None, f"Artefakt {path} SHA-256 ungueltig")
        require(path not in result, f"Manifest-Artefakt doppelt: {path}")
        result[path] = (size, digest)
    return result


def verify_manifest(root: Path, requested_profile: str | None) -> tuple[dict[str, Any], Profile]:
    manifest_bytes = read_regular(root / MANIFEST_NAME, "Stressmanifest")
    manifest = as_mapping(parse_json_bytes(manifest_bytes, "Stressmanifest"), "Stressmanifest")
    require(canonical_json(manifest) == manifest_bytes, "Stressmanifest ist nicht kanonisch serialisiert")
    digest_bytes = read_regular(root / MANIFEST_DIGEST_NAME, "Manifest-Digest")
    expected_digest_text = f"sha256:{sha256_bytes(manifest_bytes)}\n".encode("ascii")
    require(digest_bytes == expected_digest_text, "Manifest-Digest stimmt nicht oder ist nicht kanonisch")
    require(field(manifest, ("schema",), "Manifest-Schema") == SCHEMA, "Manifest-Schema ungueltig")
    version = exact_int(field(manifest, ("version", "schema_version"), "Manifest-Version"), "Manifest-Version")
    require(version == SCHEMA_VERSION, "Manifest-Version ungueltig")
    require(
        set(manifest)
        == {
            "artifacts",
            "disc",
            "formats",
            "iso_files",
            "profile",
            "provenance",
            "schema",
            "version",
            "workload",
        },
        "Manifest besitzt unerwartete oder fehlende Top-Level-Felder",
    )
    profile_name = field(manifest, ("profile",), "Manifest-Profil")
    require(isinstance(profile_name, str) and profile_name in PROFILES, "Manifest-Profil unbekannt")
    if requested_profile is not None:
        require(profile_name == requested_profile, "Manifest-Profil stimmt nicht mit --profile ueberein")
    profile = PROFILES[profile_name]
    require(
        sha256_bytes(manifest_bytes) == EXPECTED_MANIFEST_DIGESTS[profile.name],
        "Manifest-Digest weicht von der veroeffentlichten v3-Profilidentitaet ab",
    )
    provenance = as_mapping(manifest["provenance"], "Manifest-Provenienz")
    require(
        set(provenance)
        == {
            "contract_version",
            "deterministic_seed",
            "generator",
            "retail_content",
            "source_inputs",
        },
        "Manifest-Provenienz besitzt unerwartete oder fehlende Felder",
    )
    require(
        provenance["generator"] == "tools/performance/write_native_disc_cold_build_stress.py",
        "Manifest-Provenienz nennt nicht den oeffentlichen Generator",
    )
    require(
        exact_int(provenance["contract_version"], "Provenienz-Vertragsversion")
        == PROVENANCE_CONTRACT_VERSION,
        "Provenienz-Vertragsversion ungueltig",
    )
    require(
        exact_int(provenance["deterministic_seed"], "Deterministischer Seed") == 12_648_430,
        "Deterministischer Seed ungueltig",
    )
    require(provenance["retail_content"] is False, "Manifest darf keinen Retailinhalt ausweisen")
    require(provenance["source_inputs"] == [], "Manifest darf keine Quell-/Retailinputs besitzen")
    require(
        as_mapping(manifest["workload"], "Manifest-Workload") == expected_workload(profile),
        "Manifest-Workload besitzt nicht das exakte Profil",
    )
    formats = as_mapping(manifest["formats"], "Manifest-Formate")
    require(
        formats
        == {
            "root_header_size": 24,
            "root_magic": ROOT_MAGIC.decode("ascii"),
            "root_record_size": 20,
        },
        "Manifest-Formate stimmen nicht mit den Binaertabellen ueberein",
    )
    return manifest, profile


def verify_artifacts(root: Path, manifest: dict[str, Any]) -> None:
    artifacts = manifest_artifacts(manifest)
    expected = {
        "analysis.overrides",
        "disc.gdi",
        "latent-aot-entries.txt",
        "track01.bin",
        "track02.raw",
        "track03.bin",
    }
    require(set(artifacts) == expected, "Manifest besitzt nicht exakt die sechs Fixture-Artefakte")
    for path, (size, digest) in sorted(artifacts.items()):
        data = read_regular(root / path, f"Manifest-Artefakt {path}")
        require(len(data) == size, f"{path}: Manifestgroesse stimmt nicht")
        require(sha256_bytes(data) == digest, f"{path}: Manifest-SHA-256 stimmt nicht")


def verify_disc_manifest(manifest: dict[str, Any], high_sector_count: int) -> None:
    disc = as_mapping(manifest["disc"], "Manifest-Disc")
    require(
        set(disc)
        == {
            "boot_filename",
            "boot_load_address",
            "data_lba",
            "descriptor",
            "logical_sector_size",
            "raw_sector_size",
            "tracks",
        },
        "Manifest-Disc besitzt unerwartete oder fehlende Felder",
    )
    require(disc["descriptor"] == "disc.gdi", "Manifest-Disc nennt falschen Deskriptor")
    require(disc["boot_filename"] == "BOOT.BIN", "Manifest-Disc nennt falsche Bootdatei")
    load_address = disc["boot_load_address"]
    require(
        isinstance(load_address, str)
        and re.fullmatch(r"0x[0-9A-Fa-f]{8}", load_address) is not None
        and int(load_address, 16) == BOOT_ADDRESS,
        "Manifest-Disc nennt falsche Bootadresse",
    )
    require(exact_int(disc["logical_sector_size"], "Logische Sektorgroesse") == 2048, "Manifest-Disc: logische Sektorgroesse falsch")
    require(exact_int(disc["raw_sector_size"], "Rohsektorgroesse") == 2352, "Manifest-Disc: Rohsektorgroesse falsch")
    require(exact_int(disc["data_lba"], "Data-LBA") == DATA_TRACK_LBA, "Manifest-Disc: Data-LBA falsch")
    tracks = as_list(disc["tracks"], "Manifest-Tracks")
    require(
        tracks
        == [
            {
                "lba": 0,
                "number": 1,
                "path": "track01.bin",
                "sector_size": RAW_SECTOR_SIZE,
                "sectors": 24,
                "type": 4,
            },
            {
                "lba": 30,
                "number": 2,
                "path": "track02.raw",
                "sector_size": RAW_SECTOR_SIZE,
                "sectors": 4,
                "type": 0,
            },
            {
                "lba": DATA_TRACK_LBA,
                "number": 3,
                "path": "track03.bin",
                "sector_size": RAW_SECTOR_SIZE,
                "sectors": high_sector_count,
                "type": 4,
            },
        ],
        "Manifest-Tracks stimmen nicht mit dem GDI-Vertrag ueberein",
    )


def verify_iso_manifest(
    manifest: dict[str, Any],
    files: dict[str, bytes],
    entries_by_name: dict[str, DirectoryEntry],
) -> None:
    raw = field(manifest, ("iso_files",), "Manifest ISO-Dateien")
    entries = as_list(raw, "Manifest ISO-Dateien")
    manifest_order: list[str] = []
    described: dict[str, tuple[int, str]] = {}
    for index, raw_item in enumerate(entries):
        item = as_mapping(raw_item, f"Manifest ISO-Datei {index}")
        name = field(item, ("name", "path"), f"ISO-Datei {index} Name")
        require(isinstance(name, str) and name in files, f"Manifest beschreibt unbekannte ISO-Datei: {name}")
        size = exact_int(field(item, ("size", "size_bytes", "bytes"), f"ISO-Datei {name} Groesse"), f"ISO-Datei {name} Groesse")
        digest = field(item, ("sha256",), f"ISO-Datei {name} SHA-256")
        require(isinstance(digest, str) and SHA256_RE.fullmatch(digest) is not None, f"ISO-Datei {name}: SHA-256 ungueltig")
        extent_lba = exact_int(
            field(item, ("extent_lba",), f"ISO-Datei {name} Extent"),
            f"ISO-Datei {name} Extent",
        )
        require(
            extent_lba == entries_by_name[name].extent and extent_lba >= DATA_TRACK_LBA,
            f"ISO-Datei {name}: Manifest-Extent stimmt nicht",
        )
        require(name not in described, f"Manifest ISO-Datei doppelt: {name}")
        described[name] = (size, digest)
        manifest_order.append(name)
    require(manifest_order == sorted(manifest_order), "Manifest ISO-Dateien sind nicht sortiert")
    require(set(described) == set(files), "Manifest beschreibt nicht exakt alle ISO-Dateien")
    for name, data in files.items():
        size, digest = described[name]
        require(size == len(data) and digest == sha256_bytes(data), f"Manifest ISO-Datei {name} stimmt nicht")


def verify_expected_iso_set(files: dict[str, bytes], profile: Profile) -> None:
    expected = {
        "BOOT.BIN;1",
        "ROOTS.BIN;1",
        "SEMANTIC.BIN;1",
        "SEMANTIC.JSN;1",
        "WORKLOAD.JSN;1",
        "PARTS.JSN;1",
        "README.TXT;1",
    }
    expected.update(f"M{index:03d}.BIN;1" for index in range(profile.modules))
    expected.add("M000DUP.BIN;1")
    require(set(files) == expected, "ISO besitzt nicht exakt die erwarteten Stressdateien")
    expected_readme = (
        "KATANA NATIVE DISC COLD BUILD STRESS FIXTURE\n"
        "PUBLIC, DETERMINISTIC, AND RETAIL-FREE\n"
        f"PROFILE={profile.name}\n"
        "GENERATOR_SEED=12648430\n"
        "ALL BYTES ARE SYNTHETIC AND REGENERABLE FROM THE REPOSITORY WRITER.\n"
    ).encode("ascii")
    require(files["README.TXT;1"] == expected_readme, "ISO-Public-/Retail-Free-Nachweis driftet")


def verify_fixture(root_argument: Path, requested_profile: str | None) -> Fixture:
    try:
        argument_info = root_argument.lstat()
    except OSError as error:
        raise VerificationError(f"Fixture-Verzeichnis fehlt: {root_argument}") from error
    require(
        stat.S_ISDIR(argument_info.st_mode) and not root_argument.is_symlink(),
        "Fixture-Pfad ist kein sicheres Verzeichnis",
    )
    try:
        root = root_argument.resolve(strict=True)
    except OSError as error:
        raise VerificationError(f"Fixture-Verzeichnis fehlt: {root_argument}") from error
    try:
        root_info = root.lstat()
    except OSError as error:
        raise VerificationError("Fixture-Verzeichnis konnte nicht gelesen werden") from error
    require(stat.S_ISDIR(root_info.st_mode) and not root.is_symlink(), "Fixture-Pfad ist kein sicheres Verzeichnis")

    allowed_top_files = {
        MANIFEST_NAME,
        MANIFEST_DIGEST_NAME,
        "analysis.overrides",
        "disc.gdi",
        "latent-aot-entries.txt",
        "track01.bin",
        "track02.raw",
        "track03.bin",
    }
    actual_top_files: set[str] = set()
    for child in root.iterdir():
        info = child.lstat()
        require(stat.S_ISREG(info.st_mode) and not child.is_symlink(), f"Unerwarteter Nicht-Datei-Eintrag: {child.name}")
        actual_top_files.add(child.name)
    require(actual_top_files == allowed_top_files, "Fixture-Verzeichnis besitzt fehlende oder unerwartete Dateien")

    manifest, profile = verify_manifest(root, requested_profile)
    verify_artifacts(root, manifest)
    low, audio, high = parse_gdi(root)
    verify_disc_manifest(manifest, len(high) // RAW_SECTOR_SIZE)
    verify_synthetic_low_track(mode1_payload(low, "track01.bin", 0))
    verify_synthetic_audio(audio)
    files, entries = parse_iso(high)
    verify_expected_iso_set(files, profile)
    verify_iso_manifest(manifest, files, entries)
    verify_boot(files["BOOT.BIN;1"], profile)
    verify_overrides(read_regular(root / "analysis.overrides", "Analyse-Overrides"), profile)
    verify_roots(files["ROOTS.BIN;1"], profile)
    verify_workload(files["WORKLOAD.JSN;1"], profile)
    verify_partitions(files["PARTS.JSN;1"], profile)
    verify_semantic_program(files["SEMANTIC.BIN;1"], files["SEMANTIC.JSN;1"])
    verify_modules(files, profile)
    verify_latent_hints(
        read_regular(root / "latent-aot-entries.txt", "Latent-AOT-Hints"),
        files,
        entries,
        profile,
    )
    return Fixture(root, manifest, profile, files)


def snapshot(root: Path) -> dict[str, bytes]:
    result: dict[str, bytes] = {}
    for path in sorted(root.rglob("*")):
        info = path.lstat()
        require(stat.S_ISREG(info.st_mode) and not path.is_symlink(), f"Vergleich besitzt Nicht-Datei: {path}")
        relative = path.relative_to(root).as_posix()
        result[relative] = path.read_bytes()
    return result


def compare_fixtures(first: Fixture, second: Fixture) -> None:
    require(first.profile == second.profile, "--compare-Profile stimmen nicht ueberein")
    first_snapshot = snapshot(first.root)
    second_snapshot = snapshot(second.root)
    require(first_snapshot.keys() == second_snapshot.keys(), "--compare-Dateimengen stimmen nicht")
    for path, data in first_snapshot.items():
        require(data == second_snapshot[path], f"--compare ist nicht byteidentisch: {path}")


def run_disc_audit(executable: Path, fixture: Fixture) -> None:
    try:
        resolved = executable.resolve(strict=True)
    except OSError as error:
        raise VerificationError(f"--katana-cli fehlt: {executable}") from error
    require(resolved.is_file(), "--katana-cli ist keine regulaere Datei")
    try:
        completed = subprocess.run(
            [str(resolved), "disc-audit", str(fixture.root / "disc.gdi"), "--json"],
            stdin=subprocess.DEVNULL,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            timeout=120,
            check=False,
        )
    except (OSError, subprocess.TimeoutExpired) as error:
        raise VerificationError(f"disc-audit konnte nicht erfolgreich ausgefuehrt werden: {error}") from error
    stderr = completed.stderr.decode("utf-8", errors="replace").strip()
    require(completed.returncode == 0, f"disc-audit scheiterte ({completed.returncode}): {stderr}")
    try:
        report = json.loads(
            completed.stdout.decode("utf-8"),
            object_pairs_hook=unique_json_pairs,
            parse_constant=reject_json_constant,
        )
    except (UnicodeDecodeError, json.JSONDecodeError, TypeError) as error:
        raise VerificationError(f"disc-audit --json lieferte kein gueltiges JSON: {error}") from error
    require(isinstance(report, dict), "disc-audit --json lieferte kein JSON-Objekt")
    require(report.get("status") == "success", "disc-audit meldete keinen Erfolg")
    require(
        report.get("report_type") == "dreamcast_hardware_audit",
        "disc-audit lieferte den falschen Reporttyp",
    )


def build_argument_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("fixture", type=Path, help="Vom KR-4974-Writer erzeugtes Verzeichnis")
    parser.add_argument("--profile", choices=tuple(PROFILES), help="Erwartetes Profil (sonst Manifest)")
    parser.add_argument("--compare", type=Path, help="Zweite Ausgabe vollstaendig bytegenau vergleichen")
    parser.add_argument("--katana-cli", type=Path, help="Optional echten katana-recomp disc-audit --json ausfuehren")
    return parser


def main(argv: list[str] | None = None) -> int:
    arguments = build_argument_parser().parse_args(argv)
    try:
        fixture = verify_fixture(arguments.fixture, arguments.profile)
        compared = False
        if arguments.compare is not None:
            second = verify_fixture(arguments.compare, fixture.profile.name)
            compare_fixtures(fixture, second)
            compared = True
        audited = False
        if arguments.katana_cli is not None:
            run_disc_audit(arguments.katana_cli, fixture)
            audited = True
        result = {
            "basic_blocks": fixture.profile.basic_blocks,
            "byte_identical_compare": compared,
            "disc_audit": audited,
            "functions": fixture.profile.functions,
            "manifest_sha256": sha256_bytes(canonical_json(fixture.manifest)),
            "modules": fixture.profile.modules,
            "profile": fixture.profile.name,
            "roots": fixture.profile.roots,
            "schema": SCHEMA,
            "seed_waves": len(fixture.profile.wave_sizes),
            "verified": True,
        }
        sys.stdout.buffer.write(canonical_json(result))
        return 0
    except VerificationError as error:
        print(f"KR-4974-Verifikation fehlgeschlagen: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
